version: "3"
services:
    web:
        image: nginx:latest
        container_name: vs_nginx
        ports:
            - "80:80"
        volumes:
            - ./src:/code
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    php:
        build: ./php
        container_name: vs_php
        ports:
            - "9000:9000"
        working_dir: /code
        volumes:
            - ./src:/code
            - ./php/custom.ini:/usr/local/etc/php/conf.d/zzzzz-php.ini
    redis_db:
        image: redis:latest
        container_name: vs_redis_db
        ports:
            - "6379:6379"
        expose:
            - 6379
        volumes:
            - ./data/redis:/data
    database:
        image: mysql:5.7.22
        container_name: vs_mysql_db
        expose:
            - 3306
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=test
        volumes:
            - ./data/db:/var/lib/mysql
networks:
    app:
        driver: "bridge"